In [1]:
import yaml2new
import scipy.constants as const
import numpy as np
from scipy.special import lambertw


In [2]:
eda = 0.62
sigma = 5e-16

data_dic = {'params': 
                   { 'Ed_a': 'Ec-0.62' ,
                    'sigma_ea':sigma
                   }}
temps = yaml2new.getTemps(data_dic )
temps

0.62 5e-16


array([274.26471501, 298.5384835 , 327.31135228, 361.91299699])

In [8]:
Nc = 2.89e19
vth = 2.046e7
k = const.k/const.e

e = Nc*vth / 300**2 * 5e-16*temps**2 * np.exp(-eda/k/temps)
e

array([1.04979989e+00, 1.05835459e+01, 1.06925378e+02, 1.08342105e+03])

In [12]:
er = np.array([1,10,100,1000])*1.0

In [19]:
a = Nc*vth / 300**2
a *= sigma/er

b =  eda / k 

b / 2 / lambertw(-np.sqrt(a) * b / 2, tol=1e-10).real



array([274.73761151, 299.18856558, 328.22772015, 363.24295984])

In [42]:
eda = 0.62
inter = 5e9

a = Nc*vth / 300**2
a *= inter/er

b =  eda / k 

z = b/2 * np.sqrt(inter/er)
print(z)
w = lambertw(z, tol=1e-10).real
print(w)
ts = 1/w/k/2*eda
print(ts)

e = inter * ts**2 * np.exp(-eda/k/ts)
e

[2.54374637e+08 8.04403232e+07 2.54374637e+07 8.04403232e+06]
[16.54805039 15.46448034 14.38551201 13.31179087]
[217.39120513 232.62344023 250.07108655 270.2416716 ]


array([   1.,   10.,  100., 1000.])

In [44]:
# a = Nc*vth / 300**2
a = inter/er
b =  eda / k 

z = np.sqrt(a) * b / 2
w = lambertw(z, tol=1e-10).real

ts = b / 2 / w

e = inter * ts**2 * np.exp(-eda/k/ts)
z, w, ts, e

(array([2.54374637e+08, 8.04403232e+07, 2.54374637e+07, 8.04403232e+06]),
 array([16.54805039, 15.46448034, 14.38551201, 13.31179087]),
 array([217.39120513, 232.62344023, 250.07108655, 270.2416716 ]),
 array([1.e+00, 1.e+01, 1.e+02, 1.e+03]))

In [51]:

a = Nc*vth*sigma / 300**2/er
b = eda / k 

z = np.sqrt(a) * b / 2
w = lambertw(z, tol=1e-10).real

ts = b / 2 / w

e = sigma *Nc*vth/ 300**2 *ts**2 * np.exp(-eda/k/ts)
print(z, w)

ts,e

[6520100.47691417 2061836.80801989  652010.04769142  206183.68080199] [13.11652728 12.05003983 10.9907603   9.93995974]


(array([274.26471501, 298.5384835 , 327.31135228, 361.91299699]),
 array([   1.,   10.,  100., 1000.]))